---
title: "00_loader"

knit: (function(input, encoding) {
  rmarkdown::render(input,
                    encoding = "UTF-8",
                    output_dir = "../html",
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output: 
  html_document
  #pdf_document
---

```{r libraryLoader, include=FALSE}
library(knitr)
library(tinytex)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(forcats)
library(lme4)
library(lmerTest)
library(sf)
library(kableExtra)
library(sjmisc)
library(maps)
library(magrittr)
```

```{r ChunkOpts, include = TRUE, echo = FALSE}
  opts_chunk$set(echo = TRUE)

  theme_set(theme_bw(base_family = "serif"))
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r dataWrangler, include = TRUE, echo = FALSE}
#Read in the 4 csv files
athletes <- read.csv('./data/athlete_events_data_dictionary.csv', header = TRUE)
events <- read.csv('./data/athlete_events.csv', header = TRUE)
countryDefdd<- read.csv('./data/country_definitions_data_dictionary.csv',header = TRUE)
countryDef <- read.csv('./data/country_definitions.csv',header = TRUE)
locations <- read.csv('./data/country-coord.csv', header = TRUE)
```

```{r glossaryMaker, include = TRUE, echo = FALSE}
glossaryDef <- data.frame(Acronym = character(), Definition = character())
glossaryDef <- add_row(glossaryDef, Acronym = "DUMMY", Definition = "Testing to see if two rows ccan be printed")
glossaryDef <- add_row(glossaryDef, Acronym = "NOC", Definition = "National Olympic Committee")
```

```{r functionMaps, include = TRUE, echo = FALSE}
drawMap <- function(strSeason, olympicCaption){

  # Plot the information regarding all the athletes on the map
  # strSeason = "Summer"
  locations_df <- events %>% 
    distinct(NOC, Season) %>% 
    full_join(locations, by = join_by(NOC == Alpha.3.code)) %>% 
    filter((grepl(strSeason,Season)) & !is.na(Country))  %>% 
    select(region = Country, lat = Latitude..average., long = Longitude..average.)


  world_map <- map_data("world")

  # Add locations to the plot
  ggplot() #+
#    geom_map(
#      data = world_map,
#      map = world_map,
#      aes(map_id = region),
#      color = "black",
#      fill = "lightgrey",
#      linewidth = 0.5
#    ) +
#    theme_void() +
#    geom_point(
#      data = locations_df,
#      aes(x = long, y = lat, color = region),
#      size = 3,
#      shape = 20
#    ) +
    #theme(panel.background = element_rect(fill = "lightblue"),
    #      panel.grid = element_blank()) +
    #scale_color_discrete(name = "Locations") +
    #labs(title = olympicCaption) +
    #theme(legend.position="none")
  }
```

```{r functionGoldtable, include = TRUE, echo = FALSE}
MedalWinners <- function(strSeason) {
  print("Hello World")
 events %>% 
    filter(grepl(strSeason,Season) & !is.na(Medal)) %>% 
    select(Games, Year, Sport, Event, Medal) %>% 
   group_by(Games, Year, Sport) %>% 
   summarize(totalcount = n())
#    %>% 
#    knitr::kable("latex", position = "H",  booktabs = T,
#             caption = "Testing",
#             label = "Winners") %>%  
#    kable_styling(latex_options = "striped")
}
```