---
title: "07_Exploritory"

knit: (function(input, encoding) {
  rmarkdown::render(input,
                    encoding = "UTF-8",
                    output_dir = "../html",
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output: 
  bookdown::pdf_document2
---

```{r child = 'src/00_loader.Rmd', Include = TRUE, eval = FALSE}
```

When loading in the data I have determined from the events table, the variables Sex, NOC, Season, and medals are all factor variables and needed to be coded this way in R. 



Table \@ref(tab:SummerWinners)

Table \@ref(tab:WinterWinners)


```{r summerTables, warning = FALSE, echo = FALSE}
summer1 <- MedalWinners("Summer", 1896)
summer2 <- MedalWinners("Summer", 2016)

list(summer1,summer2) %>% 
  kableExtra::kable("latex", position = "H",  booktabs = T,
         label = "SummerWinners",
         caption = "Number of medal winners in 1896 versus 2016 Summer Olympic Games",) %>% 
         kable_styling(latex_options = "striped")
```
\newpage

```{r winterTables, warning=FALSE, echo=FALSE}

winter1 <- MedalWinners("Winter", 1924)
winter2 <- MedalWinners("Winter", 2014)

list(winter1,winter2) %>% 
  knitr::kable("latex", position = "H",  booktabs = T, caption = "Winter Sport Total Medals won",
         label = "WinterWinners") %>%  
         kable_styling(latex_options = "striped")
```

```{r summerBreaks, warning = FALSE, echo = FALSE}
summer1 <- MedalBreakDown("Summer", 1896)
summer2 <- MedalBreakDown("Summer", 2016)

list(summer1,summer2) %>% 
  kableExtra::kable("latex", position = "H",  booktabs = T,
         label = "SummerBreakDownWinners",
         caption = "Medal allocation for 1896 versus 2016 Summer Olympic Games",) %>% 
         kable_styling(latex_options = "striped")
```

```{r winterBreaks, warning=FALSE, echo=FALSE}

winter1 <- MedalBreakDown("Winter", 1924)
winter2 <- MedalBreakDown("Winter", 2014)

list(winter1,winter2) %>% 
  kableExtra::kable("latex", position = "H",  booktabs = T,
         label = "WinterBreakDownWinners",
         caption = "Medal allocation for 1924 versus 2014 Winter Olympic Games",) %>% 
         kable_styling(latex_options = "striped", font_size = 7)
```

```{r summerBreaksTeam, warning = FALSE, echo = FALSE}
summer1 <- MedalBreakDownByTeam ("Summer", 1896)
summer2 <- MedalBreakDownByTeam ("Summer", 2016)

list(head(summer1,10),head(summer2,10)) %>% 
  kableExtra::kable("latex", position = "H",  booktabs = T,
         label = "SummerBreakDownWinnersTeam",
         caption = "Medal allocation for 1896 versus 2016 Summer Olympic Games by Team",) %>% 
         kable_styling(latex_options = "striped", font_size = 7)
```



