---
title: 'Assignment 3 - Final Report'
subtitle: 'Setting the environment'
author: "Sharon Van Den Berg"
date: "2025-03-24"
knit: (function(input, encoding) {
  rmarkdown::render(input,
                    encoding = "UTF-8",
                    output_dir = "../report",
                    
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output: 
  #html_document:
  bookdown::pdf_document2:
    latex_engine: lualatex
  tufte::tufte_handout:
    latex_engine: xelatex
  includes:
      #in_header: 00_Globals.sty
      #before_body: 00_Title.sty
      #after_body: tail.sty
      toc: yes
      keep_tex: yes
      number_sections: yes
geometry: margin= 2.00cm
font-size: 11pt
font-style: "Times New Roman"
line-spacing: 1.5
header-includes:
  - \usepackage{setspace}
  - \onehalfspacing
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \lhead{\fontsize{11pt}{11pt}\selectfont "Times New Roman"}
  - \fancyhead[L]{\fontsize{11}{11}\selectfont STAT950/STAT250 ASSESSMENT 03 - Sharon Van Den Berg 9251936}
  - \fancyhead[R]{}
  - \lfoot{\fontsize{11pt}{11pt}\selectfont "Serif"}
  - \fancyfoot[C]{\thepage}
  - \fancyfoot[L]{}
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
editor_options: 
  chunk_output_type: console
bibliography: DSAA811.bib
link-citations: TRUE
citation_package: apa-annotated.csl
---

[This report was made using R Markdown as a project linking to my Git account](https://github.com/stvdb914/DSAA811-Preliminary-Report "Git Repository")
	
```{r child = 'src/00_loader.Rmd' , eval = TRUE}
```

\newpage

# Abstract
```{r child = 'src/01_Abstract.Rmd'}
```

# Glossary
```{r Glossary, include = TRUE, echo = FALSE}
  options(knitr.kable.NA = '')

    glossaryDef %>% 
    knitr::kable("pipe", 
                 booktabs = TRUE) %>% 
    kable_styling(latex_options = "striped", position = "left") %>% 
      column_spec(1, bold = TRUE)

  
```


```{=tex}
  %Display the table of contents and bypass the R commands to do this
  \newpage
  \tableofcontents
  \newpage
```


# Introduction

```{r child = 'src/02_Introduction.Rmd'}
```

# Background
```{r child = 'src/03_Background.Rmd'}
```

# Research questions and aims of the project
```{r child = 'src/04_ResearchQuestions.Rmd'}
```

# Rationale
```{r child = 'src/05_Rational.Rmd'}
```

# Data Description
```{r child = 'src/06_DataDescription.Rmd'}
```

# Exploritory data analysis
```{r child = 'src/07_Exploritory.Rmd'}
```
# Conclusion / Discussion
```{r child = 'src/08_Conclude.Rmd'}
```
\newpage

#Session Information

```{r sessionInfo}
sessionInfo()
```

\newpage
# Bibliography